//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cisti
    {
        public string SpremacicaJMBG_R { get; set; }
        public int KabinetBroj { get; set; }
    
        public virtual Spremacica Spremacica { get; set; }
        public virtual Kabinet Kabinet { get; set; }
    }
}
