//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drzi
    {
        public string VlasnikJMBG_V { get; set; }
        public string DirektorJMBG_R { get; set; }
        public int PrivatnaSkolaRegBroj { get; set; }
    
        public virtual Vlasnik Vlasnik { get; set; }
        public virtual Direktor Direktor { get; set; }
        public virtual PrivatnaSkola PrivatnaSkola { get; set; }
    }
}
