//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDBContext : DbContext
    {
        public ModelDBContext()
            : base("name=ModelDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grad> Gradovi { get; set; }
        public virtual DbSet<Ucenik> Ucenici { get; set; }
        public virtual DbSet<Zivi> Zivis { get; set; }
        public virtual DbSet<Roditelj> Roditelji { get; set; }
        public virtual DbSet<PrivatnaSkola> PrivatneSkole { get; set; }
        public virtual DbSet<Pohadja> Pohadjas { get; set; }
        public virtual DbSet<Zaposleni> Zaposlenis { get; set; }
        public virtual DbSet<Predmet> Predmeti { get; set; }
        public virtual DbSet<Kabinet> Kabineti { get; set; }
        public virtual DbSet<Cisti> Cistis { get; set; }
        public virtual DbSet<Cuva> Cuvas { get; set; }
        public virtual DbSet<Vlasnik> Vlasnici { get; set; }
        public virtual DbSet<Drzi> Drzis { get; set; }
        public virtual DbSet<PraviUgovor> PraviUgovors { get; set; }
        public virtual DbSet<Ugovor> Ugovori { get; set; }
    }
}
