//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PraviUgovor
    {
        public string Nacin_Placanja { get; set; }
        public int UgovorBrojUgovora { get; set; }
        public string DirektorJMBG_R { get; set; }
        public string RoditeljJMBG_Rod { get; set; }
    
        public virtual Direktor Direktor { get; set; }
        public virtual Roditelj Roditelj { get; set; }
    }
}
