//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        public string JMBG_R { get; set; }
        public string Godine { get; set; }
        public string Ime_R { get; set; }
        public string Prezime_R { get; set; }
        public int PrivatnaSkolaRegBroj { get; set; }
        public string Uloga { get; set; }
    
        public virtual PrivatnaSkola PrivatnaSkola { get; set; }
    }
}
